# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 90

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 30

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security
  - bug
  - high priority

# Label to use when marking as stale
staleLabel: staled

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in the past 90 days. It is scheduled to be closed in 30 days, unless
  someone give it some loving in the meantime.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been closed because nobody has shown it love in the past 120
  days; poor thing. Comments are still open if someone wants to revive it.
